### PR TITLE
SDK 48 'Modular Headers' Fix

### LINKED ISSUE #15: Expo Dev Client Build Crashes: use_modular_headers!
I have installed WatermelonDB, and the Config-Plugin.
Then i wanted to create a development build with expo for the IOS simulator.

The build crashed when installing the pods.
```
...
Installing libevent (2.1.12)
Installing libvmaf (2.3.0)
Installing libwebp (1.2.4)
Installing react-native-safe-area-context (4.5.0)
Installing react-native-skia (0.1.172)
Installing simdjson (3.1.0-wmelon1)
[!] The following Swift pods cannot yet be integrated as static libraries:
The Swift pod `WatermelonDB` depends upon `simdjson`, which does not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.
```

Did I forget to setup something?

This is how the plugins part of my app.json looks
```
"plugins": [
      "@morrowdigital/watermelondb-expo-plugin",
      [
        "expo-build-properties",
        {
          "android": {
            "kotlinVersion": "1.6.10"
          }
        }
      ],
      [
        "expo-image-picker",
        {
          "photosPermission": "The app accesses your photos to let you preview your tattoos"
        }
      ]
    ]
```

Thanks

### PR DESCRIPTION
**Pull request by TheLonelyAstronaut**
This small PR fixes #15 - EAS build for SDK48 and WatermelonDB v0.26.0

### CODE REVIEW

**Comment by brunokiafuka** [comment]
Hi @TheLonelyAstronaut thanks for making this fix, will you be able to rebase your branch so we can safely merge.

**Comment by brunokiafuka** [comment]
One last request please test it under `example/*` by upgrading the watermelon version on example app.

**Review by brunokiafuka — APPROVED** [review]

**Comment by TheLonelyAstronaut** [comment]
@brunokiafuka are you able to test a plugin by building expo dev client? Looks like it's compiles fine, but when you try to use  complex models (with lazy decorators, actions and so on) it just crashes with "undefined is not an object"

**Comment by brunokiafuka** [comment]
> @brunokiafuka are you able to test a plugin by building expo dev client? Looks like it's compiles fine, but when you try to use complex models (with lazy decorators, actions and so on) it just crashes with "undefined is not an object"

I've made a few tweaks but all runs fine, just testing with  watermelon `v0.26.0`

**Comment by TheLonelyAstronaut** [comment]
@brunokiafuka tested with lazy, its fine. But adding @actions brakes all, could you share example?

**Comment by brunokiafuka** [comment]
you can branch out the basic starter example on the project [here](https://github.com/morrowdigital/watermelondb-expo-plugin/tree/main/example)

**Comment by TheLonelyAstronaut** [comment]
@brunokiafuka huh, sorry, i picked an example from Watermelon repo, it has old library version with deprecated @action hook, all is fine

**Pull request merged**
